project:
  type: website
  resources:
    - _redirects

execute:
  freeze: auto

website:
  title: "Paul Simmering"
  site-url: "https://simmering.dev"
  search: true
  navbar:
    right:
      - about.qmd
      - text: Blog
        href: blog.qmd
      - publications.qmd
      - talks.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/psimm
      - icon: linkedin
        href: https://www.linkedin.com/in/paulsimmering
  page-footer: |
    <a href="/blog.xml">Subscribe via RSS</a> | <a href="/imprint.html">Imprint</a> | <a href="/privacy.html">Privacy policy</a> | This website doesn't use cookies.<script data-goatcounter="https://simmering.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
format:
  html:
    date-format: "YYYY-MM-DD"
    theme:
      light: theme-light.scss
      dark: theme-dark.scss
    css:
      - fonts.css
      - styles.css
    linkcolor: "#2563eb"
    highlight-style:
      light: custom-light.theme
      dark: custom-dark.theme
    code-overflow: wrap
    code-copy: hover
    code-block-border-left: "#64748b"
    mainfont: "Inter, -apple-system, BlinkMacSystemFont, sans-serif"
    monofont: "JetBrains Mono, Consolas, monospace"
